unikraft/docs

- content/en/community/contacts.md
- content/en/community/events.md
Review content in community area.
> Content review

- content/en/docs/develop/booting.md
I've added some more details about the booting process, starting from loading the image into memory, going to ukboot.
> content/docs: Update booting documentation content

- content/en/_index.md
- content/en/blog/2022-02-05-new-site-and-unikraft-at-fosdem22.md
- content/en/releases/v0.7.0.md
Still TODO, I will force push later.
> Release v0.7.0 with accompanying blog post

- content/en/community/_index.md
Add general information on the Unikraft open source community, resources and development model.
> Fill community index page

- content/en/docs/concepts/_index.md
'mute' is the wrong word there; I am guessing 'moot' was intended.
> Grammar fix in _index.md

- content/en/_index.md
Fix: Update some links from the front page
Resolve #23
> Fix: Update some links from the front page

- content/en/blog/2022-03-16-unikraft-gsoc-org.md
Signed-off-by: Alexander Jung <alex@unikraft.org>
> content/en/blog: Entry about GSoC

- content/en/docs/features/security.md
Signed-off-by: Alexander Jung <alex@unikraft.org>
> content/docs/features: Add security features page

- content/en/blog/2022-02-17-unikraft-at-asplos22.md
Signed-off-by: Alexander Jung <alex@unikraft.org>
> content/blog: Update ASPLOS article with award

- content/en/docs/contributing/review-process.md
The efficiency requirements paragraph from the `Review process`
topic is incomplete. This commit adds the missing content.
Signed-off-by: Răzvan Vîrtan <virtanrazvan@gmail.com>
> content/docs/contributing: Complete the `Review process` section

- content/en/community/hackathons/2022-05-lyon/challenges/index.md
Add link to Google spreadsheet highlighting challenges.
> lyon-hack: Add challenges

- content/en/community/hackathons/2022-05-lyon/_index.md
> hack-lyon: Update list of winners

- content/en/blog/2022-05-21-unikraft-gsoc-org.md
Add post about accepted GSoC22 projects.
> blog: Add post about accepted GSoC22 projects

- content/en/blog/2022-07-05-unikraft-gsoc-shadow-stack.md
Signed-off-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>
> content/en/blog: Add shadow stack gsoc blog post

- content/en/blog/2022-07-05-unikraft-gsoc-intel-sgx.md
Signed-off-by: Xiangyi Meng <xymeng16@gmail.com>
> content/en/blog: GSoC Intel SGX Blog

- content/en/community/hackathons/2022-10-munich/_index.md
Add landing page for Munich hackathon
> hackatons: Add landing page for Munich hackathon

- .github/workflows/config/config.json
- .github/workflows/linter.yml
- .github/workflows/rules/common/inlineTokenChildren.js
- .github/workflows/rules/common/wordPattern.js
- .github/workflows/rules/md101.js
- .github/workflows/rules/md102.js
- .github/workflows/rules/md103.js
- .github/workflows/rules/md104.js
- .github/workflows/rules/rules.js
Signed-off-by: Radu Nichita <radunichita99@gmail.com>
> Add linting workflow

- .gitignore
Ignore temporary and swap files
> Ignore temporary and swap files

- content/en/community/hackathons/sessions/basic-app-porting/content/Overview.md
- content/en/community/hackathons/sessions/basic-app-porting/content/Overview_Compiling-the-Application-from-Source.md
- content/en/community/hackathons/sessions/basic-app-porting/content/Overview_Creating-a-Boilerplate-Microlibrary-for-Your-Application.md
- content/en/community/hackathons/sessions/basic-app-porting/content/Overview_Identifying-a-Candidate-Application.md
- content/en/community/hackathons/sessions/basic-app-porting/content/Overview_Invoking-the-Application's-`main`-Method.md
- content/en/community/hackathons/sessions/basic-app-porting/content/Overview_Patching-the-Application.md
- content/en/community/hackathons/sessions/basic-app-porting/content/Overview_Providing-Build-Files.md
- content/en/community/hackathons/sessions/basic-app-porting/content/Overview_Setting-up-Your-Workspace.md
- content/en/community/hackathons/sessions/basic-app-porting/content/Overview_Starting-with-a-Linux-User-Space-Build.md
- content/en/community/hackathons/sessions/basic-app-porting/content/Overview_The-Unikraft-Build-Lifecycle.md
- content/en/community/hackathons/sessions/basic-app-porting/content/Overview_Using-Your-Library-in-a-Unikraft-Unikernel-Application.md
- content/en/community/hackathons/sessions/basic-app-porting/content/Reminders_Configuring,-Building-and-Running-Unikraft.md
- content/en/community/hackathons/sessions/basic-app-porting/content/Work-Items_01.-Port-`libfortune`-to-Unikraft.md
- content/en/community/hackathons/sessions/basic-app-porting/content/Work-Items_02.-Add-Fortunes-to-Unikraft's-Boot-Sequence.md
- content/en/community/hackathons/sessions/basic-app-porting/content/Work-Items_03.-Create-a-Patch-to-Introduce-a-New-Fortune.md
- content/en/community/hackathons/sessions/basic-app-porting/content/Work-Items_04.-Give-Us-Feedback.md
- content/en/community/hackathons/sessions/basic-app-porting/content/Work-Items_Support-Files.md
- content/en/community/hackathons/sessions/basic-app-porting/index.md
feat: Update basic-app-porting session
Signed-off-by: Gabriel Mocanu <gabi.mocanu98@gmail.com>
> hack/usoc22: Update basic-app-porting session

- content/en/community/hackathons/sessions/basic-app-porting/index.md
- content/en/community/hackathons/usoc22/basic-app-porting/index.md
fix: Move quiz to usoc22 folder
Signed-off-by: Gabriel Mocanu <gabi.mocanu98@gmail.com>
> fix: Move quiz to usoc22 folder

- content/en/blog/2022-08-22-unikraft-gsoc-intel-sgx-3.md
Signed-off-by: Xiangyi Meng <xymeng16@gmail.com>
> content/en/blog: add gsoc sgx 3rd post

- content/en/blog/2022-07-05-unikraft-gsoc-intel-sgx.md
Signed-off-by: Xiangyi Meng <xymeng16@gmail.com>
> content/en/blog: fixed where the author is not shown

- content/en/blog/2022-10-08-unikraft-hacktoberfest.md
Signed-off-by: Radu Nichita <radunichita99@gmail.com>
> docs/blog: Add blogpost for Unikraft Hacktoberfest '22

- .github/workflows/config/config.json
> github/linter: Remove bash command prefix check

- content/en/community/hackathons/2022-10-munich/_index.md
Add Nitinder Mohan to organizing team.
> hack/munich22: Add Nitinder Mohan to organizing team

- content/en/community/hackathons/2022-10-munich/baby-steps/index.md
- content/en/community/hackathons/2022-10-munich/complex-applications/index.md
Signed-off-by: Radu Nichita <radunichita99@gmail.com>
> hack/munich22: Fix title for session 01 and session 04

- content/en/community/hackathons/2022-10-munich/intro/index.md
Add contents for intro section.
> hack/munich22: Add contents for intro section

- content/en/community/hackathons/2022-10-munich/baby-steps/demo
- content/en/community/hackathons/2022-10-munich/baby-steps/sol
- content/en/community/hackathons/2022-10-munich/baby-steps/work
- content/en/community/hackathons/2022-10-munich/debugging/demo
- content/en/community/hackathons/2022-10-munich/debugging/images
- content/en/community/hackathons/2022-10-munich/debugging/sol
- content/en/community/hackathons/2022-10-munich/debugging/work
Signed-off-by: Radu Nichita <radunichita99@gmail.com>
> hack/munich22: fix wrong symlinks

- content/en/community/hackathons/sessions/complex-applications/content/Work-Items_01.-SQLite-(Tutorial).md
Fix links to libraries in "Complex Applications" session
> hackathons: Fix links to libraries in "Complex Applications" session

- content/en/_index.md
- content/en/blog/2022-12-02-unikraft-releases-janus.md
- content/en/releases/v0.11.0.md
Announce release 0.11 (Janus). Highlight most relevant topics and community activities.
> blog: Add announcement for release 0.11 (Janus)

- content/en/community/hackathons/2022-10-munich/challenges/index.md
Detail challenge types for Munich hackathon (October 22-23, 2022).
> hack/munich22: Detail challenge types

- content/en/docs/getting-started/_index.md
Covers: #60 #58 #57 
Will need rebasing after #125 and #124 are merged.
> docs/getting-started: Add deps for different linux distributions

- content/en/community/hackathons/2023-03-athens/_index.md
So that @michpappas is trully happy!
> hack-athens23: Make landing page 100% perfect

- content/en/docs/develop/booting.md
adapted the file and function names to the current repository
> booting.md: Fix x86_64 boot explanation

- content/en/community/hackathons/2023-03-athens/_index.md
> hack-athens23: Add guest talks

- content/en/community/hackathons/2023-03-athens/complex-applications/images
- content/en/community/hackathons/2023-03-athens/complex-applications/index.md
- content/en/community/hackathons/2023-03-athens/complex-applications/sol
- content/en/community/hackathons/2023-03-athens/complex-applications/work
- content/en/community/hackathons/sessions/complex-applications/content/Work-Items_01.-SQLite-(Tutorial).md
- content/en/community/hackathons/sessions/complex-applications/content/Work-Items_02.-SQLite-New-Filesystem-(Tutorial).md
- content/en/community/hackathons/sessions/complex-applications/content/Work-Items_03.-Redis-(Tutorial).md
- content/en/community/hackathons/sessions/complex-applications/content/Work-Items_06.-Nginx.md
- content/en/community/hackathons/sessions/complex-applications/sol/01-set-up-and-run-sqlite/Makefile
- content/en/community/hackathons/sessions/complex-applications/sol/02-change-filesystem-sqlite/Makefile
- content/en/community/hackathons/sessions/complex-applications/sol/03-set-up-and-run-redis/Makefile
- content/en/community/hackathons/sessions/complex-applications/sol/04-obtain-the-ip-statically/Makefile
- content/en/community/hackathons/sessions/complex-applications/sol/05-benchmark-redis/Makefile
- content/en/community/hackathons/sessions/complex-applications/sol/06-set-up-and-run-nginx/Makefile
Mostly copied from the [Munich hackathon](https://github.com/unikraft/docs/blob/main/content/en/community/hackathons/2022-10-munich/intro/index.md#setup).
> hack/athens: Add initial complex applications page

- content/en/community/hackathons/2023-03-athens/intro/index.md
Mostly copied from the [Munich hackathon](https://github.com/unikraft/docs/blob/main/content/en/community/hackathons/2022-10-munich/intro/index.md#setup).
> hack/athens: Add initial intro page

- content/en/_index.md
- static/assets/imgs/figs/power-usage.svg
Reference https://www.raspbian.org/
> frontpage: Fix Raspbian typo

- content/en/community/hackathons/2023-04-amsterdam/_index.md
- content/en/community/hackathons/2023-04-amsterdam/behind-scenes/demo
- content/en/community/hackathons/2023-04-amsterdam/behind-scenes/images
- content/en/community/hackathons/2023-04-amsterdam/behind-scenes/index.md
- content/en/community/hackathons/2023-04-amsterdam/behind-scenes/sol
- content/en/community/hackathons/2023-04-amsterdam/behind-scenes/work
- content/en/community/hackathons/2023-04-amsterdam/bincompat/demo
- content/en/community/hackathons/2023-04-amsterdam/bincompat/index.md
- content/en/community/hackathons/2023-04-amsterdam/bincompat/work
- content/en/community/hackathons/2023-04-amsterdam/complex-applications/images
- content/en/community/hackathons/2023-04-amsterdam/complex-applications/index.md
- content/en/community/hackathons/2023-04-amsterdam/complex-applications/sol
- content/en/community/hackathons/2023-04-amsterdam/complex-applications/work
- content/en/community/hackathons/2023-04-amsterdam/setup/index.md
- content/en/community/hackathons/sessions/setup/content/Setup.md
- content/en/community/hackathons/sessions/setup/content/Setup_Docker-Setup.md
- content/en/community/hackathons/sessions/setup/content/Setup_Linux-Environment.md
- content/en/community/hackathons/sessions/setup/content/Setup_Setup-Checks.md
- content/en/community/hackathons/sessions/setup/content/Setup_Virtual-Machine.md
- content/en/community/hackathons/sessions/setup/index.md
Add session contents for the Amsterdam Unikraft Hackathon (April 15-16, 2023)
> `hack/amsterdam23`: Contents for the Amsterdam Unikraft Hackathon

- content/en/community/hackathons/2023-04-amsterdam/challenges/index.md
> hack/amsterdam23: Add challenges page

- content/en/community/hackathons/2023-10-sosp/_index.md
- content/en/community/hackathons/2023-10-sosp/behind-scenes/demo
- content/en/community/hackathons/2023-10-sosp/behind-scenes/images
- content/en/community/hackathons/2023-10-sosp/behind-scenes/index.md
- content/en/community/hackathons/2023-10-sosp/behind-scenes/sol
- content/en/community/hackathons/2023-10-sosp/behind-scenes/work
- content/en/community/hackathons/2023-10-sosp/bincompat/demo
- content/en/community/hackathons/2023-10-sosp/bincompat/index.md
- content/en/community/hackathons/2023-10-sosp/bincompat/work
- content/en/community/hackathons/2023-10-sosp/complex-applications/images
- content/en/community/hackathons/2023-10-sosp/complex-applications/index.md
- content/en/community/hackathons/2023-10-sosp/complex-applications/sol
- content/en/community/hackathons/2023-10-sosp/complex-applications/work
- content/en/community/hackathons/2023-10-sosp/setup/index.md
Add proposed contents of [SOSP'23](https://sosp2023.mpi-sws.org/) Unikraft tutorial.
> `hackathons`: Add SOSP'23 tutorial

- content/en/community/hackathons/2023-05-porto/_index.md
Update Google Maps link. Update contact information for Tiago Viana.
> hack/porto23: Update contact information

- content/en/community/hackathons/sessions/behind-scenes/content/Required-Tools-and-Resources_Support-Files.md
- content/en/community/hackathons/sessions/behind-scenes/content/Work-Items_01.-Set-Up.md
- content/en/community/hackathons/sessions/behind-scenes/content/Work-Items_06.-Tutorial---Reminder:-Adding-Filesystems-to-an-Application.md
Add missing links to repositories.
> sessions/behind-scenes: Fix links

- content/en/docs/getting-started/_index.md
Signed-off-by: Tim Beermann <beermann@osism.tech>
> docs/getting-started: Remove one unnecessary word

- content/en/community/hackathons/2023-05-porto/intro/index.md
This is mostly an adapred copy of the intro sessions of the `Athens` and `Amsterdam` hackathons.
> hackathons/porto: Add intro session

- content/en/blog/2023-05-15-unikraft-releases-atlas.md
Fix typos and inconsistencies in 0.13 release post
> blog: Fix typos and inconsistencies in 0.13 release post

- content/en/community/hackathons/usoc23/overview/index.md
Add the first session, `Overview of Unikraft`. The participants will setup their environments and run the already ported applications.
> hack/usoc23: Add session 01 - Overview of Unikraft

- content/en/community/hackathons/sessions/bincompat/content/Work-Items_00.-Setup.md
- content/en/community/hackathons/sessions/bincompat/content/Work-Items_01.-Run-Binary-Applications.md
- content/en/community/hackathons/sessions/bincompat/content/Work-Items_01_2.-Flavors-of-the-ELF-Loader.md
- content/en/community/hackathons/sessions/bincompat/content/Work-Items_01_3.-Behind-the-Scenes.md
- content/en/community/hackathons/sessions/bincompat/content/Work-Items_02.-Build-app-elfloader.md
- content/en/community/hackathons/sessions/bincompat/content/Work-Items_03.-Doing-It-Manually.md
- content/en/community/hackathons/sessions/bincompat/content/Work-Items_05.-Run-Custom-Application.md
- content/en/community/hackathons/sessions/bincompat/content/Work-Items_06.-Create-your-Own-Application.md
- content/en/community/hackathons/sessions/bincompat/content/Work-Items_07.-Debugging-Binary_Compatibility.md
- content/en/community/hackathons/usoc23/bincompat/index.md
Update the `bincompat` session from `hackathons/sessions/` and refer it from the USoC23 session 04, Binary Compatibility.
Closes: #256
> USoC'23: Update session 04 - Binary Compatibility

- content/en/community/hackathons/sessions/debugging/content/Debugging.md
- content/en/community/hackathons/sessions/debugging/content/Debugging_KVM_Linuxu.md
- content/en/community/hackathons/sessions/debugging/content/Practical-Work_01.-Tutorial.-Use-GDB-in-Unikraft.md
- content/en/community/hackathons/sessions/debugging/content/Practical-Work_02.-Mystery:-Find-the-secret-using-GDB.md
- content/en/community/hackathons/sessions/debugging/content/Practical-Work_03.-Bug-or-feature?.md
- content/en/community/hackathons/sessions/debugging/content/Practical-Work_06.-Nginx-with-or-without-main?-That's-the-question..md
- content/en/community/hackathons/sessions/debugging/content/Practical-Work_07.-Bonus.-Bad-ELF-in-Town.md
- content/en/community/hackathons/sessions/debugging/content/Reminders.md
- content/en/community/hackathons/sessions/debugging/content/intro.md
- content/en/community/hackathons/usoc23/debugging/index.md
This pull request introduces the fifth session about debugging under Unikraft. This session goes over common debugging techniques and how we can use them on Unikraft.
> hack/usco23: Introduce section 05: Debugging

- content/en/community/hackathons/usoc23/challenges/index.md
Make several updates:
* update internal section link
* align section headers (use double `#`)
* add challenges on building and testing with VMware and Hyper-V
> hackathons/usoc23: Make updates to challenges page

- content/en/community/hackathons/2023-09-vancouver/_index.md
> hack-vancouver23: Add thanks to Margo Seltzer

- content/hackathons/2023-09-vancouver/index.mdx
Improve initial setup information. Add @StefanJum as host. Update schedule, including links to corresponding guides.
> `hack-vancouver23`: Update landing page

- content/guides/bincompat.mdx
Rebased on top of #315 for the linter output. Will remove that after it is merged.
> Stefan jum/guides/add bincompat

- .gitignore
Signed-off-by: cristian-vijelie <cristianvijelie@gmail.com>
> docs: Add node_modules to .gitignore

- .gitignore
Signed-off-by: cristian-vijelie <cristianvijelie@gmail.com>
> docs: Ignore generated files

- README.md
Signed-off-by: cristian-vijelie <cristianvijelie@gmail.com>
> Update running instructions

- content/docs/concepts/index.mdx
> index.mdx: Add missing word

- content/blog/2024-01-02-unikraft-releases-telesto.mdx
- content/releases/v0.16.0.mdx
- src/components/landing-hero.tsx
Add blog post, notes and support files for release 0.16.0 (Telesto).
> release: Add blog post and notes for release 0.16.0

- content/blog/2024-02-13-unikraft-releases-v0.16.2.mdx
- content/releases/v0.16.2.mdx
- src/components/landing-hero.tsx
Add blog post, notes and support files for release 0.16.2 (Telesto).
> release: Add blog post and notes for release 0.16.2

- content/en/blog/2023-08-24-unikraft-gsoc-enhancing-vscode-developer-experience.md
4th blog for GSoC's IDE extension project
> blog: 4th blog for GSoC's IDE extension project

- content/en/blog/2023-08-02-unikraft-gsoc-enhancing-vscode-developer-experience.md
3rd blog for GSoC's IDE extension project
> blog: 3rd blog for GSoC's IDE extension project

- content/en/blog/2023-07-14-unikraft-gsoc-arm-cca-2.md
- content/en/blog/2023-08-04-unikraft-gsoc-arm-cca-3.md
> blog: Add blog post for Arm CCA project (Part 3)

- content/docs/faq.mdx
Add common pitfalls from using / building Unikraft.
> docs/faq: Add common pitfalls

- content/docs/faq.mdx
> `docs`: Fix FAQ items

- content/docs/faq.mdx
Add information on debugging `kraft run` commands.
> docs: Add / Update FAQ items on debugging kraft run

- content/blog/2024-03-20-unikraft-releases-v0.16.3.mdx
- content/releases/v0.16.3.mdx
- src/components/landing-hero.tsx
Add blog post, notes and support files for release 0.16.3 (Telesto).
> release: Add blog post and notes for release 0.16.3

- content/docs/contributing/adding-to-the-app-catalog.mdx
Add detailed information about using Docker and about exporting the filesystem.
Fix minor typos and formatting issues.
> docs: Improve the app catalog contributing guide

- content/blog/2024-06-07-unikraft-releases-v0.17.0.mdx
- content/releases/v0.17.0.mdx
- src/components/landing-hero.tsx
Add blog post, notes and support files for release 0.17.0 (Telesto).
> release: Add blog post and notes for release 0.17.0

- content/blog/2024-06-18-unikraft-gsoc-lxboot_x86.mdx
The first blog post for lxboot x86
> Add blog entry for lxboot x86

- content/blog/2024-06-19-gsoc-environment-variables.mdx
Added the first blog post for GSoC'24 with the progress I have made.
> content/blog: Add blog post for GSoC'24: Env Var for Unikraft Builds

- content/hackathons/usw24/index.mdx
Update USW application deadline for June 29, 2024, 10pm CEST.
> hack/usw24: Update deadline for June 29, 2024, 10pm CEST

- content/hackathons/usw24/index.mdx
Add link to playlist with recordings of initial presentations for each session.
> usw24: Add link to recordings

- content/blog/2024-08-01-gsoc-multiboot2.mdx
Added the third GSoC blog post about Multiboot2 showcasing the progress made during the third set of 3 weeks.
Signed-off-by: Maria Pana [maria.pana4@gmail.com](mailto:maria.pana4@gmail.com)
> content/blog: Add third GSoC blog post about Multiboot2

- content/docs/contributing/coding-conventions.mdx
- content/docs/internals/build-system.mdx
- content/docs/internals/syscall-shim.mdx
> fix(docs): Update or remote outdated links

- content/hackathons/usw25/index.mdx
Update the sessions to change the focus of the workshops to the Unikraft internals.
The sessions will be:
* Overview of Unikraft - running basic applications using already provided scripts.
* Behind the Scenes - running applications without any scripts, use make, menuconfig, qemu, dig into the external/internal libraries, etc.
* Debugging in Unikraft - use gdb to attach to a running unikernel.
* Basic Application Porting - port some basic applications, without requiring new external libraries to be ported.
* Binary Compatibility - run applications using the elfloader.
* Advanced Application Porting - port more complex applications that include the need for new external libraries to be ported.
> hackathons/usw25: Update sessions and details

- content/blog/2025-05-15-multiprocess.mdx
Technical blog post on multiprocess support introduced in 0.19.0.
> blog: Add blog post on multiprocess support

- content/blog/2025-05-23-unikraft-releases-v0.19.0.mdx
- content/releases/v0.19.0.mdx
- src/components/landing-hero.tsx
Add blog post, notes and support files for release 0.19.0 (Pan).
> release: Add blog post and notes for release 0.19.0

- content/guides/overview.mdx
- content/hackathons/usw25/index.mdx
Update the Overview guide to use the catalog-core scripts and add USW25 session 01.
> usw25: Add session 1, Overview

- content/blog/2025-07-17-unikraft-releases-v0.19.1.mdx
- content/releases/v0.19.1.mdx
- src/components/landing-hero.tsx
Add blog post, notes and support files for release 0.19.1 (Pan).
> release: Add blog post and notes for release 0.19.1
