unikraft/docs

- content/en/docs/_index.md
Links were placeholder links. Now they are fixed to properly point to existing content.
> docs: Fix links on main documentation page

- content/en/community/hackathons/2022-05-lyon/_index.md
Add Gaulthier to people. Mark Hugo and Gaulthier as onsite and Pierre and Razvan as online.
> hack-lyon: Update people

- content/en/community/hackathons/2022-06-aachen/_index.md
Hackathon will take place on June 25-26, 2022, at RWTH Aachen.
> hackathons: Add entry for Unikraft Aachen Hackathon

- content/en/docs/getting-started/_index.md
The current Getting Started page only describes how to setup and build Unikraft with `kraft`. However, sometimes it makes sense to work with a `Makefile` directly. This commit adds a description on how to do this.
> Add Makefile build to Getting Started

- content/en/blog/2022-08-21-unikraft-ioapic.md
This commit adds a blog on I/O APIC support for unikraft
Signed-off-by: Sairaj Kodilkar <skodilkar7@gmail.com>
> content/en/blog: Add I/O APIC support blog

- .github/workflows/rules/md104.js
The linter detects `:` and `;` as end of sentence, wich `gives multiple sentences per line` errors when not needed.
This commit only interprets `.`, `?` and `!` as end of sentence.
e.g. "List of items: item 1, item 2." is misinterpreted as 2 sentences.
> github/linter: Fix the end of sentence detection

- .github/workflows/rules/md101.js
The linter checks for keywords and requires them
to be fenced by backticks.
`true` and `false` should not be marked as keywords since they are used a lot in natural language.
> github/linter: Remove unnecessary keywords `true` and `false`

- .github/workflows/rules/md104.js
The linter checks for . ? ! outside an escaped sequence. The backticks set the outside variable as `!outside`, while the parentheses set it as true or false, depending of the context. This does not work when backticks are used inside parentheses, making the text between the backticks be interpreted as unescaped.
i.e. "This sentence (having this `.escaped` sequence)." 
gives a linter error, detecting the dot inside backticks as end of sentence.
This commit changes that, using a different variable for checking if we are inside backticks.
Closes: #123 
> github/linter: Fix sentence end inside backticks

- content/en/community/hackathons/2022-10-munich/_index.md
New deadline for registration is Friday, October 14, 2022, 11am CEST.
> hack/munich22: Update registration deadline

- .github/workflows/rules/md101.js
- .github/workflows/rules/md104.js
- content/en/docs/develop/porting.md
For some reason it seems like the `patching` part of the `porting` section was missed when adding content from [`USoC'21` - basic app porting](https://usoc21.unikraft.org/docs/sessions/08-basic-app-porting/#patching-the-application).
> docs/porting: Add patching an application section

- content/en/docs/usage/dependencies.md
Add usage of `UK_WORKDIR`, `UK_ROOT` `UK_LIBS` and `UK_APPS`
environment variables and `UK_WORKDIR` directory structure.
Used docs from USoC session-01-baby-steps.
Signed-off-by: Sergiu Moga <sergiu.moga@protonmail.com>
> usage/dependencies: Add UK_WORKDIR structure

- content/en/docs/develop/syscall-shim.md
This commit adds old documentation on the use
of the syscall shim layer.
Closes: #118 
Signed-off-by: Simon Kuenzer <simon.kuenzer@neclab.eu>
> docs/develop: Add syscall shim layer old docs

- content/en/community/hackathons/sessions/behind-scenes/content/Work-Items_01.-Tutorial---Reminder:-Building-and-Running-Unikraft.md
- content/en/community/hackathons/sessions/behind-scenes/content/Work-Items_08.-Tutorial:-Arguments-from-Command-Line.md
- content/en/community/hackathons/sessions/debugging/content/Debugging_Using-GDB.md
- content/en/community/hackathons/sessions/debugging/work/01-gdb-tutorial/kvm_gdb_debug
Use of "-serial stdio" fails on systems without a graphical user interface; "-nographic" works.
> hackathons: Replace "-serial stdio" with "-nographic"

- content/en/docs/contributing/submitting-changes.md
Fix/Remove link in `submitting-changes` page.
> docs: Fix/Remove link in submitting-changes page

- content/en/docs/features/security.md
- Update state of PAuth, BTI, MTE, RNG to upstream
- Add missing links to PRs
- Separate entries for arm64 and x86_64 RNG
> docs/features/security: Update status of arm64

- layouts/_default/baseof.html
Since there is not a `thumbnail` field in the
main page header, a default one is loaded from
an image on the main page, but it's not the
Unikraft logo.
This commit adds the Unikraft logo as a thumbnail
for all the pages in the website.
> layout: Change the default website thumbnail

- CONTRIBUTING.md
The contributing file is roughly copied from the [main `Unikraft` repo](https://github.com/unikraft/unikraft/blob/staging/CONTRIBUTING.md).
Closes: #167 
> Add `CONTRIBUTING.md` file referencing the website

- .github/workflows/.textlintrc
Accept "website" and "build system" and do not issue errors to use "site" and "build tool".
You can test by installing [`textlint`]() and [`textlint-rule-methodology`]():
```console
$ npm install textlint
$ npm install textlint-rule-terminology
```
and creating a `test.md` file:
```console
$ echo 'website build system repo' > test.md
```
then running:
```console
$ npx textlint --config .github/workflows/.textlintrc test.md 
```
Only the `repo` term should issue an error. `website` and `build system` will not issue an error.
> .github: Add configuration file for textlint

- .github/workflows/rules/md104.js
When using shortcodes, we should ignore the "one line per sentence and
one sentence per line" linter rule.
This however requires the hugo shortcodes to extend on more than one line.
More precisely, the line that contains the closing `}}` marks is not considered inside a hugo shortcode.
For example:
```md
{{ [...] some. text! with? many: punctuation. marks. [...] }}
```
will still fail, but
```md
{{ [...]
[...] some. text! with? many: punctuation. marks. [...]
[...] }}
```
will pass the tests.
> github/linter: Ignore md104 rule when inside shortcodes

- content/en/docs/getting-started/_index.md
This is related to this [issue](https://github.com/unikraft/unikraft/issues/449).
It should be merged after #50, for the github token reference.
> docs/getting-started: Add the kraft list update step

- .github/workflows/rules/md101.js
When adding images in `Hugo`, the linter picks them up as keywords and requires them to be inside backticks.
> github/linter: Remove `.png` keyword

- content/en/docs/usage/install.md
The current step does not work, the new one does.
See https://pip.pypa.io/en/stable/topics/vcs-support/
```
$ pip3 install https://github.com/unikraft/kraft.git@stable
Collecting https://github.com/unikraft/kraft.git@stable
HTTP error 404 while getting https://github.com/unikraft/kraft.git@stable
Could not install requirement https://github.com/unikraft/kraft.git@stable because of error 404 Client Error: Not Found for url: https://github.com/unikraft/kraft.git@stable
Could not install requirement https://github.com/unikraft/kraft.git@stable because of HTTP error 404 Client Error: Not Found for url: https://github.com/unikraft/kraft.git@stable for URL https://github.com/unikraft/kraft.git@stable
```
> Fix kraft via pip installation step

- content/en/docs/usage/dependencies.md
This will add some duplicate information with the pr #45, but I thought that it is important for the GitHub token usage to be on the `Ecosystem` page, since it's an error that will occur in a very early stage of using `kraft`, and it should not only be explained in the `advanced usage` page.
> usage/dependencies: Add GitHub token usage

- content/en/docs/develop/porting.md
Closes: #117 
Port the informations on the [Makefile.uk](https://github.com/unikraft/unikraft/blob/RELEASE-0.7.0/doc/guides/developers-app.rst#makefileuk), [exportsyms.uk](https://github.com/unikraft/unikraft/blob/RELEASE-0.7.0/doc/guides/developers-app.rst#exportsymsuk) and [extra.ld](https://github.com/unikraft/unikraft/blob/RELEASE-0.7.0/doc/guides/developers-app.rst#extrald) files from the Unikraft [old documentation](https://github.com/unikraft/unikraft/blob/RELEASE-0.7.0/doc/guides/developers-app.rst).
I also added the fix of linter errors in this pr so the linter check would be more readable.
I added the commits from #125 and #124 to fix some unnecessary linter errors.
I will rebase and remove those 2 commits after the linter prs are merged.
> Port the informations on the Makefile.uk, exportsyms.uk and extra.ld files from the Unikraft old documentation.

- content/en/docs/usage/advanced/kraft_advanced.md
Add the `kraft advanced usage` file, describing in more details the `kraft` tool.
Some of the content was taken from USoC2021, sessions 1-4.
Signed-off-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>
Signed-off-by: Sergiu Moga <sergiu.moga@protonmail.com>
Signed-off-by: Gabriel Mocanu <gabi.mocanu98@gmail.com>
> usage/kraft_advanced: Add kraft advanced docs

- content/en/community/hackathons/2023-03-athens/_index.md
Add Aristotelis Kretsis as organizer for the Unikraft Athens hackathon (March 30-31, 2023)
> hack-athens23: Add Aristotelis Kretsis as organizer

- content/en/community/hackathons/2023-03-athens/_index.md
Use Sunday, March 26, 2023 as the registration deadline.
> hack-athens23: Update registration deadline

- content/en/community/hackathons/2023-03-athens/_index.md
Use EET (Eastern European Time, Athens timezone) instead of CET (Central European Time).
> hack-athens23: Update timezone

- content/en/docs/contributing/testing.md
This PR adds a new way of running the `checkpatch.pl` script. Currently, the documentation mentioned running the coding-style checker only for a specific number of commits rather than for the file itself before committing. 
Closes #180.
Signed-off-by: Radu Nichita [radunichita99@gmail.com](mailto:radunichita99@gmail.com)
> docs/testing: Add more ways of running checkpatch

- content/en/community/hackathons/2023-04-amsterdam/_index.md
Hackathon is host by VUA / VUSec. It will take place on Saturday and Sunday, April 15-16, 2023.
> Add landing page for Amsterdam'23 hackathon

- content/en/community/hackathons/2023-04-amsterdam/_index.md
Use "Amsterdam" instead of "Amsteradam".
> hack-amsterdam23: Fix typo in title

- content/en/docs/usage/bin_compat.md
Add a new page on using Unikraft in binary compatibility mode.
Most of the contents were taken from the hackathon sessions and `app-elfloader`s `README.md` file.
This covers only the usage of the `app-elfloader`, the debugging part will come later, and will likely not be part of the `usage/` files.
Closes: #207
> docs/usage: Add binary compatibility usage

- content/en/community/hackathons/2023-04-amsterdam/_index.md
Add 4 guest talks to be presented by VUA PhD students and researchers.
> hack-amsterdam23: Add guest talks

- content/en/community/hackathons/2023-05-porto/_index.md
Hackathon takes place at Faculdade de Engenharia Universidade do Porto in May 2023.
> Add landing page for Porto 2023 hackathon

- content/en/community/hackathons/2023-04-amsterdam/bincompat/index.md
- content/en/community/hackathons/sessions/bincompat/content/Overview_01.-The-Process-of-Loading-and-Running-an-Application-with-Binary-Compatibility.md
- content/en/community/hackathons/sessions/bincompat/content/Work-Items_00.-Setup.md
- content/en/community/hackathons/sessions/bincompat/content/Work-Items_01.-Run-Binary-Applications.md
- content/en/community/hackathons/sessions/bincompat/content/Work-Items_02.-Build-app-elfloader.md
- content/en/community/hackathons/sessions/bincompat/content/Work-Items_03.-Doing-It-Manually.md
- content/en/community/hackathons/sessions/bincompat/content/Work-Items_06.-Create-your-Own-Application.md
Update to the most recent version of `app-elfloader`, `run-app-elfloader`. Use `scripts` repository in `unikraft-upb`.
> sessions/bincompat: Update contents to use unikraft-upb/scripts

- content/en/docs/usage/make_build.md
This PR adds documentation for building and running complex applications on `x86` and `AArch64`.
It goes into detail regarding configuration steps and manual launch commands for the make build system.
Depends on having these PRs merged:
* [core Unikraft virtio PR](https://github.com/unikraft/unikraft/pull/519)
* [`newlib` PR](https://github.com/unikraft/lib-newlib/pull/21)
Signed-off-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>
> docs/usage: Add build and run complex apps doc

- content/en/docs/contributing/coding-style.md
This pr fixes the typo in "Coding Style" page under "Contributing" of the main website.
"In the future, me might provide... change this code." -> "In the future, we might provide... changes this code."
I'm new to open source, and wasn't really sure if creating an issue was a good idea since it's a single word change.
I'll create one if requested by the reviewers :)
Signed-off-by: Taemin Ha taemin.ha@utexas.edu
> Fixed typo in Coding Style page

- content/en/community/hackathons/usoc23/_index.md
We extended the registration deadline by a few days because of some late announcments.
> hackathon/usoc23: Update registration deadline

- data/papers.yaml
this is related to issue #270 
there's a paper named "FlexOS: Towards Flexible OS Isolation" lack of property `link`.Because of it,when we click title "FlexOS: Towards Flexible OS Isolation", it will not jump to the related links.
> doc/publications: Add correct link to FlexOS paper

- content/en/community/hackathons/usoc23/baby-steps/index.md
- content/en/community/hackathons/usoc23/behind-the-scenes/index.md
- content/en/community/hackathons/usoc23/overview/index.md
- content/en/community/hackathons/usoc23/registration-challenges/_index.md
The sessions rendering order was wrong, since the `weight` attribute was not set in the index files header.
> usoc23: Fix sessions rendering order

- content/en/community/hackathons/2023-09-vancouver/_index.md
New registration deadline for the Vancouver Unikraft Hackathon be Sunday, September 17, 2023, 11pm PDT.
> hack-vancouver23: Update registration deadline

- content/en/blog/2023-07-10-unikraft-gsoc23.md
Add information on the five selected GSoC'23 projects: link to blog post, student and mentors. Detailed information on each project is part of the corresponding blog post.
> blog: Add info on selected GSoC'23 projects

- Dockerfile
* Updates node version to 14.
* Adds the node version as an `ARG` to Dockerfile
> Add node version as ARG to Dockerfile

- content/guides/bincompat.mdx
- content/hackathons/2023-09-aveiro/index.mdx
Add links to the Aveiro hackathon front page that will point to the guides.
Most of the instructions will be placed inside application repositories, the guides will mainly send people there.
> Stefan jum/link aveiro hackathon to guides

- data/papers.yaml
Add our Loupe ASPLOS'24 paper. ASPLOS'24 is the 28th edition of the ACM International Conference on Architectural Support for Programming Languages and Operating Systems. The paper, "Loupe: Driving the Development of OS Compatibility Layers", was accepted to appear in Volume 1. The methods described in this paper were central to the early development of Unikraft.
NOTE: The DOI URL does not resolve yet, but it is valid and will point to the ACM paper page once it is up.
More info: https://www.asplos-conference.org/asplos2024/
> Add Loupe ASPLOS'24 paper

- configs/internals.sidebar.json
- content/docs/internals/cross-compiling.mdx
Add clang cross compilation for both `x86` and `AArch64`.
> internals: Add cross-compiling with `clang` doc

- configs/internals.sidebar.json
The cofing conventions are under `contributing/`, not under `internals/`. This would result in a 404 error.
> configs/internals: Remove reference to coding conventions

- content/guides/bincompat.mdx
The path to the syscall-shim was relative to the guides directory. Updated to an absolute path.
> bincompat.mdx: Updated the path to syscall-shim

- content/guides/bincompat.mdx
Replace 'binray' with 'binary'.
> guides/bincompat.mdx: Fix "binray" typo

- content/guides/bincompat.mdx
> guides/bitcompat.mdx: Fix typo

- content/guides/bincompat.mdx
Fixed "nount" typo to "mount".
> bincompat.mdx: Fix "nount" typo

- content/docs/internals/build-system.mdx
Update the link for Linux kernel tree documentation.
> /internals/build-system.mdx: Update link for documentation 

- content/guides/bincompat.mdx
Reshuffle the word order: "an application dynamic binary" -> "a dynamic binary application"
> guides/bincompat.mdx: Reshuffle the words order

- content/hackathons/2023-10-sosp/index.mdx
Add session links for SOSP tutorial / hackathon. Session links point to guides pages.
> hackathons/sosp-23: Add links to content sessions

- content/docs/contributing/kraftkit.mdx
- content/docs/contributing/unikraft.mdx
The `KraftKit` contributing page has the same format as the `Unikraft core` contributing page, which has been modified to reflect the conventions used in the `KraftKit` development.
GitHub-fixes: https://github.com/unikraft/docs/issues/370
> feat: Add `KraftKit` contributing page

- content/en/blog/2023-07-12-unikraft-gsoc-packaging-libs-2.md
As part of the "Packaging Pre-built Micro-libraries for Faster and More Secure Builds" GSoC'23 project, this blog post details work in the second 3 weeks of GSoC, together with planned work for the upcoming 3 weeks.
> blog: Add blog post for GSoC'23: Packaging micro-lib (Part 2)

- content/docs/faq.mdx
Port FAQs from the old documentation website.
> docs/faq: Update FAQs list

- content/guides/using-the-app-catalog.mdx
- Updated the Nginx version in the `kraft run` command from `unikraft.org/nginx` to `unikraft.org/nginx:1.15`.
- Replaced a deprecated network command with its updated equivalent.
> Updated Nginx Version And Network Syntax

- content/docs/cli/install.mdx
Signed-off-by: Alexander Jung <alex@unikraft.io>
> fix(cli): Add information about RPM and Arch install guides

- content/docs/cli/filesystem.mdx
- content/docs/cli/packaging.mdx
- content/docs/concepts/virtualization.mdx
- content/docs/internals/architecture.mdx
- content/docs/internals/build-system.mdx
I've been learning about Unikraft and have started by going through the documentation, which I've found really interesting and instructive! Thanks for the effort you've put into it.
I found a few typos or corrections that could be made, so here's a little PR to improve it a bit. :)
> Fixing some typos in the documentation

- content/hackathons/2024-05-zagreb/index.mdx
Add landing page for Zagreb Unikraft Hackathon taking place as part of DORS / CLUC at the Algebra University, on Saturday-Sunday, May 18-19, 2024.
> hackathons: Add landing page for Zagreb Unikraft Hackathon

- content/hackathons/2024-05-zagreb/index.mdx
Svebor Prstacic is the lead contact for DORS / CLUC.
> hack/zagreb: Add Svebor Prstacic to hosts

- content/blog/2024-05-10-unikraft-gsoc24.mdx
Announce GSoC'24 Unikraft projects. Announce projects, applicants and mentors.
> blog: Announce GSoC'24 participants

- content/blog/2024-06-16-unikraft-gsoc-port-mimalloc-to-unikraft.mdx
Signed-off-by: Yang Hu <yanghuu531@gmail.com>
> blog: Add GSoC'24 blog post on porting the mimalloc memory allocator to Unikraft

- content/blog/2024-07-10-gsoc-multiboot2.mdx
Added the second GSoC blog post about Multiboot2 showcasing the progress made during the second set of 3 weeks.
Signed-off-by: Maria Pana <maria.pana4@gmail.com>
> content/blog: Add second GSoC blog post about Multiboot2

- content/blog/2024-07-10-unikraft-gsoc-lxboot_x86.mdx
Add second blog post for GSoC'24: Linux x86 Boot Protocol Support
> Add second blog post

- content/blog/2024-06-16-unikraft-gsoc-port-mimalloc-to-unikraft.mdx
- content/blog/2024-07-12-unikraft-gsoc-test-mimalloc-on-unikraft.mdx
Signed-off-by: Yang Hu [yanghuu531@gmail.com](mailto:yanghuu531@gmail.com)
> blog: Add GSoC'24 post on testing mimalloc memory allocator

- content/community/about.mdx
- content/docs/cli/install.mdx
- content/docs/contributing/adding-to-the-app-catalog.mdx
- content/docs/internals/writing-tests.mdx
- content/guides/baby-steps.mdx
- content/guides/catalog-behind-the-scenes.mdx
This PR fixes typo in the content folder in the subfolders `community`, `docs/cli`, `docs/contributing`, `docs/internal`, and `guides`.
This is my first PR, so every suggestion on how to improve in the future the review process, how to correctly describe the issue and what has been done is well accepted 😄
> fix: typos in content folder

- content/blog/2024-08-01-unikraft-gsoc-debugging-mimalloc.mdx
Signed-off-by: Yang Hu [yanghuu531@gmail.com](mailto:yanghuu531@gmail.com)
> blog: Add GSoC'24 blog on debugging mimalloc port

- content/docs/concepts/virtualization.mdx
Fixed the numbering in the description for Figure 1.
> docs/concepts: Fix description for Figure 1

- content/blog/2024-08-22-unikraft-gsoc-benchmarking-mimalloc.mdx
Signed-off-by: Yang Hu [yanghuu531@gmail.com](mailto:yanghuu531@gmail.com)
> blog: Add GSoC'24 final blog on benchmarking mimalloc

- content/guides/debugging.mdx
This PR adds steps to disable compiler optimization for debugging purposes.
> Add tips for disabling compiler optimization in debug guide

- content/docs/cli/install.mdx
fixes the path of the config file to the correct filepath according to the official documentation under https://learn.microsoft.com/en-us/windows/wsl/wsl-config#wslconfig
reason:
Both files are config files for wsl2 but they have distinct config options and those stated to use are in the file .wslconfig inside the windows filesystem.
> fixes the path of the .wslconfig file

- content/hackathons/2024-12-vienna/index.mdx
- src/components/landing-hero.tsx
Update LATEST link. Use "Unikraft Cloud" instead of "KraftCloud". Use "workshop" instead of "hackathon".
> workshop-vienna: Update contents (names and links)

- content/hackathons/2024-12-vienna/index.mdx
Add simple instructions on using the scripts on `catalog-core` and the simple commands in the `README`s tldr.
> hackathons/vienna: Add instructions on `catalog-core`

- content/hackathons/2024-12-vienna/index.mdx
Replace TODOs with links to the spreadsheet containing the tasks.
> hackathons/vienna: Add links to the tasks spreadsheet

- .github/workflows/config/config.json
The linter checks if the first line in the file is a top-level heading.
This does not work with markdown files that are included in other files, not used as such (e.g. files under `hackathons/sessions/*/content/`).
> .github/workflows: Remove top level heading check

- content/blog/2024-12-21-unikraft-releases-v0.18.0.mdx
- content/releases/v0.18.0.mdx
- src/components/landing-hero.tsx
Add blog post, notes and support files for release 0.18.0 (Helene).
> release: Add blog post and notes for release 0.18.0

- content/blog/2025-05-22-unikraft-gsoc25.mdx
Use 2025 as year for GSoC name, instead of the current incorrect value: 2024.
> blog/gsoc25: Fix year
